/**
 * brewlog.api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomAttributeTypedArgument } from './customAttributeTypedArgument';
import { MemberInfo } from './memberInfo';


export interface CustomAttributeNamedArgument { 
    memberInfo?: MemberInfo;
    typedValue?: CustomAttributeTypedArgument;
    readonly memberName?: string | null;
    readonly isField?: boolean;
}

